# Generated by Django 5.2.16 on 2026-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sign_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
