# Generated by Django 5.2.16 on 2026-09-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('CL1', 'Classe 1'), ('CL2', 'Classe 2')], max_length=3)),
                ('backing', models.CharField(choices=[('alu_brut', 'Dos alu brut'), ('ral', 'Alu RAL au choix')], max_length=10)),
                ('prix_vente_ht', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cout_achat_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delai', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['schedule_size', 'classe', 'backing'],
            },
        ),
        migrations.CreateModel(
            name='PriceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('size_kind', models.CharField(choices=[('single', 'Single dimension'), ('diameter', 'Diameter'), ('rect', 'Width × Height')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('triangle', 'Triangle'), ('round', 'Rond'), ('square', 'Carré'), ('octagon', 'Octogone'), ('diamond', 'Losange'), ('rect', 'Rectangle'), ('directional', 'Directionnel'), ('unknown', '—')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='backing',
            field=models.CharField(blank=True, choices=[('alu_brut', 'Dos alu brut'), ('ral', 'Alu RAL au choix')], max_length=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='classe',
            field=models.CharField(blank=True, choices=[('CL1', 'Classe 1'), ('CL2', 'Classe 2')], max_length=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.pricecell'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.priceschedule'),
        ),
        migrations.CreateModel(
            name='PriceScheduleSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=30)),
                ('side_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('diameter_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('epaisseur_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('poids_note', models.CharField(blank=True, max_length=50)),
                ('rails_mm', models.CharField(blank=True, max_length=50)),
                ('transport_dpd', models.CharField(blank=True, max_length=100)),
                ('transport_palette', models.CharField(blank=True, max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.priceschedule')),
            ],
            options={
                'ordering': ['schedule', 'id'],
                'unique_together': {('schedule', 'size_label')},
            },
        ),
        migrations.AddField(
            model_name='pricecell',
            name='schedule_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='catalog.priceschedulesize'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='schedule_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.priceschedulesize'),
        ),
        migrations.AlterUniqueTogether(
            name='pricecell',
            unique_together={('schedule_size', 'classe', 'backing')},
        ),
    ]
