# Generated by Django 5.2.16 on 2026-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_categories_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceschedulesize',
            name='rails_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
